trigger:
- develop

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  project: '**/Trm.MaLogger.App.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: gitversion/setup@0
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0

- task: UseDotNet@2
  displayName: 'Use .NET Core 7.0 sdk'
  inputs:
    packageType: 'sdk'
    version: '7.0.x'
    
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


- task: DotNetCoreCLI@2
  name: 'Publish'
  displayName: 'Publish '
  inputs:
    command: 'publish'
    publishWebProjects: false #selecting the web project below; true chooses first project in solution
    projects: '$(project)'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
 


- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts'
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureRmWebAppDeployment@4
  name: 'Deploy'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '$(AZURE_SUBSCRIPTION)'
    appType: 'webApp'
    WebAppName: 'malogger-dev'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'